module.exports={menu: require("./configurations/menu.js"),
                web: require("./configurations/web.js"),
                qrcode: require("./configurations/qrcode.js"),
                server: require("./configurations/server.js"),
                easyChat: require("./configurations/easyChat.js"),
                database: require("./configurations/database.js"),
                customizedWifs: require("./configurations/customizedWifs.js"),
                mobAddr: require("./configurations/mob_addresses.js"),
                auth: require("./configurations/auth.js")};
